apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudshop
  template:
    metadata:
      labels:
        app: cloudshop
    spec:
      containers:
      - name: cloudshop
        image: 767828738042.dkr.ecr.us-east-1.amazonaws.com/poc/cloudshop
        ports:
        - containerPort: 8000