# apiVersion: v1
# kind: Service
# metadata:
#   name: cloudshop
# spec:
#   selector:
#     app: cloudshop
#   ports:
#   - port: 80
#     targetPort: 8000
# apiVersion: v1
# kind: Service
# metadata:
#   name: cloudshop
# spec:
#   type: LoadBalancer
#   selector:
#     app: cloudshop
#   ports:
#     - port: 80
#       targetPort: 8000
apiVersion: v1
kind: Service
metadata:
  name: cloudshop
spec:
  type: LoadBalancer
  selector:
    app: cloudshop
  ports:
    - port: 80
      targetPort: 5000   # MUST match containerPort
      protocol: TCP